### ISSUE TITLE
Do we want Album pages to be thumbnails?

### ISSUE THREAD

**Issue by kylemarsh** [agile-leaf/50mm#20]
Ever since we added pages for individual images, I've felt like the full-sized photos on the album pages were clunky and wanted to make those into thumbnails, I've got a change to the CSS to make the album page more of a set of thumbnails (and somewhat responsive!), but I want to make sure it works with resizing services before I submit a pull request for it (hence my recent interest in the thumbor support). For the moment, see http://photos.kmarsh.net/bm2017/ for an example of what I've done.

That said, I'm aware that one of the design goals for 50mm is to keep the project very simple, and the features I've been adding can be considered bloat. They're what *I* want out of my gallery software, but not necessarily what everyone (or the project owners/maintainers) want. I also made my changes directly in static/album.css, which is not configurable by the site/album config file, so done that way it'd be a permanent, whole-project change and wouldn't be tunable at all. I could probably put the CSS in the templates instead so that users can configure it (per site or maybe per album) but again, that adds further complexity to the software.

If this seems like something you'd like to include in 50mm I can see about cleaning up the tweaks I made and creating a polished pull request.

**Comment by arahayrabedian** [comment]
personally, I'm a fan of the thumbnail style you've got going there - I wouldn't even mind it being the default (and/or configurable). That said - @theonejb is the main maintainer here so I'd swing it by him first.

**Comment by kylemarsh** [comment]
Sounds good. What say you, @theonejb?

**Comment by theonejb** [comment]
Hey guys! Nice to see activity on this project. 👍 

Personally, I don't mind changing the default layout of the album page, as long as the current one is still usable, because that's the one I prefer. Personally, I like it because it's easy to look through old photos in a list, rather than having to open them in a new tab. But that's a personal preference.

Honestly, I'm not sure how to approach this. Any ideas on how to keep this configurable to support both our preferences, and maybe others in the future?

How about allowing overriding of CSS files? I'm thinking, a default CSS file shipped with the code, and configuration to allow overriding it.

One problem I can see with that is resizing images. Right now, the album page explicitly resizes the images, this is done to allow faster viewing. The resizing is configured via the template (there's a function call in the template with a sizing parameter). So maybe to support custom CSS, we need to support custom templates as well?

Thoughts?
